package com.muchen.tweetstormmaker.androidui.model

enum class NotificationEnum {
    LOGIN_SUCCESSFUL,
    LOGIN_FAILED,
    SEND_TWEETSTORM_SUCCESSFUL,
    SEND_TWEETSTORM_FAILED_SOME_TWEETS_SENT,
    SEND_TWEETSTORM_FAILED_NO_TWEET_SENT,
    UNSEND_TWEETSTORM_SUCCESSFUL,
    UNSEND_TWEETSTORM_FAILED_SOME_TWEETS_UNSENT,
    UNSEND_TWEETSTORM_FAILED_NO_TWEET_UNSENT,
    UNSEND_TWEETSTORMS_SUCCESSFUL,
    UNSEND_TWEETSTORMS_FAILED_NO_TWEET_UNSENT,
    UNSEND_TWEETSTORMS_FAILED_NO_TWEETSTORM_UNSENT,
    UNSEND_TWEETSTORMS_FAILED_SOME_TWEETSTORMS_UNSENT
}